GET http://localhost:3000/states/

###
GET http://localhost:3000/states/33

###
GET http://localhost:3000/districts/321

###
POST http://localhost:3000/districts/

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
DELETE http://localhost:3000/districts/322

###
PUT http://localhost:3000/districts/321

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
GET http://localhost:3000/states/21/stats/

###
GET http://localhost:3000/districts/5/details/